# Generated by Django 4.0 on 2022-06-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shuttle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuttle_licence_plate', models.CharField(blank=True, max_length=20, verbose_name='Номер автомобиля')),
                ('shuttle_color', models.CharField(blank=True, max_length=50, verbose_name='Марка автомобиля')),
                ('shuttle_model', models.CharField(blank=True, max_length=50, verbose_name='Модель автомобиля')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='auth.user')),
            ],
        ),
    ]
