# Generated by Django 4.0 on 2022-06-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dots', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dot',
        ),
    ]
