# Generated by Django 4.0 on 2022-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dots', '0002_delete_dot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название точки', models.CharField(max_length=200)),
            ],
        ),
    ]
