# Generated by Django 4.0 on 2022-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dots', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dot',
            name='Название точки',
        ),
        migrations.AddField(
            model_name='dot',
            name='dot_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название точки'),
        ),
    ]
