# Generated by Django 4.0 on 2022-06-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dots', '0004_remove_dot_название точки_dot_dot_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='dot_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название точки'),
        ),
    ]
