# Generated by Django 4.0 on 2022-06-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shuttles', '0002_shuttle_shuttle_brand_alter_shuttle_shuttle_color'),
        ('dots', '0004_remove_dot_название точки_dot_dot_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateTimeField(auto_now_add=True)),
                ('end_dot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_dot', to='dots.dot')),
                ('start_dot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_dot', to='dots.dot')),
                ('trip_shuttle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Шаттл', to='shuttles.shuttle')),
            ],
        ),
    ]
