# Generated by Django 4.0 on 2022-06-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuttles', '0002_shuttle_shuttle_brand_alter_shuttle_shuttle_color'),
        ('trips', '0002_alter_trip_trip_shuttle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_shuttle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Шаттл', to='shuttles.shuttle'),
        ),
    ]
